const enlaces = {
    enlace1:  "uno.html",
    enlace2: "dos.html",
    enlace3: "tres.html",
    enlace4: "cuatro.html",
    enlace5: "cinco.html",    
    enlace6: "seis.html",    
    enlace7: "siete.html", 
    enlace8: "ocho.html", 
    enlace9: "nueve.html", 
    enlace10: "diez.html", 
    enlace11: "once.html",
    enlace12: "Doce.html",  
    enlace13: "trece.html", 
    enlace14: "catorce.html", 
};
